---
- name: First Play - Docker Image Build 1
  hosts: docker
  tasks:
    - name: Copy Dockerfile
      copy:
       src: Dockerfile
       dest: /home/ansadmin/
    - name: Copy Artifact
      copy:
       src: target
       dest: /home/ansadmin
    - name : Build image
      command: docker build -t mohan230899/mavenwebapp .
    - name : Push Docker Image
      command: docker push mohan230899/mavenwebapp
- name: Second Play - K8s Deployment
  hosts: eks
  tasks:
   - name: 
     copy:
       src: k8s-deploy.yml
       dest: /home/ansadmin
   - name: k8s delete Deployment
     command: kubect delete deployment mavenwebappdeployment 
   - name : K8S Deployment
     command: kubectl apply -f k8s-deploy.yml
